image: python:3.7-stretch


stages:
  - lint
  - run

before_script:
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install pipenv
  - pipenv install

flake8:
  stage: lint
  script:
    - pipenv run lint

pages:
  stage: run
  script:
    - pipenv run start
  after_script:
    - mkdir public
    - mv metrics.txt public/
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
