image: python:3.7-stretch

variables:
  TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
  # $TWINE_USERNAME
  # $TWINE_PASSWORD


stages:
  - lint
  - run
  - deploy

.install_dependencies: &install_dependencies
  before_script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install pipenv
    - pipenv install --dev --deploy

flake8:
  stage: lint
  <<: *install_dependencies
  script:
    - pipenv run lint
  except:
    - tags

pages:
  stage: run
  <<: *install_dependencies
  script:
    - pipenv run start
  after_script:
    - mkdir public
    - mv metrics.txt public/
  artifacts:
    expire_in: 1 week
    paths:
      - public
  only:
    - master
  cache:
    key: language_cache
    paths:
     - language_cache.pickle


deploy:
  stage: deploy
  <<: *install_dependencies
  script:
    - pip install -U pip
    - pip install -U setuptools
    - pip install -U wheel
    - python setup.py sdist bdist_wheel
    - twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD dist/*
  only:
    - tags
