language: python
python:
- 3.6
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run lint
deploy:
  provider: pypi
  user: max-wittig
  password:
    secure: mKJFQL4G1UQFwtowcoX28vjhPLgjnwwYYrcKGaxxFI93Y9yjiP6IvTWKDfJ2Z1Pc0sPhVvy81e2wNw59jSdKE2k7Kl16ol/8PSzMgB7VY6Wm5+od95LIPO3vYZkx6eXiGZprq4ky9SUgz+RMEYDqaNW19MJ4nUyfY9d8oTgrEpkdvmJvlV4NwMP3DaMivQsdUMDsISiIX9LOjjD5xcSOEtkIU2RTl/J2yIAbm67lMp2MvXGplkXPeg1B5UaXokWPagYSjpfh/YXxh71Zcv3gOq273IMh0BCl2J9bowdrX+PunO0vkST/28VAQGZK2FxHN2p1bsASAbbDmZBuawcSQuhbX1KUZj+wtNr/TQazMGplw9OhWGSRKer37bPSEC+3YH1wMBayGDKAr2QKA718+LqDmTQum7EOHqQ/OBKNfDgOxymOTCGmCitJMxGkXPhSdnoeTQ2mHF8Cp7D3DJr4RqtBHa6VwnzV7qIrxeq5nVq8Rlj9rryrFRm1BeFIjnD2k4a3KTCDf05uLEGGtqA5MdkO7QTNMe6YNeTaRVMGKqU3XHGCE34cIxp8koVtpiR25NtZzEFnP4HOWyBI9uioL97fHDiDOy0M5Wwm7x9g0QmEqMbC+J51S0Jv26eLUYOhKCU04UTt8wkagaZ4U+oeFXa9YOCBqCV9vCKOeaDxsDY=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
