language: python
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run lint
deploy:
  - provider: pypi
    user: max-wittig
    password:
      secure: "aNeHfZbZbvU0Ew0cR0ptlJTCdL80vXPnRkhCh2+cGiiMm2YRghDOKmyq1Rmw9UXXN82k0K4WbLGGRa6R0eCL1tZ/amhsVd+o3gSMAv+JE2yDxB7KLirq2xpWazQ14C7VPuUUZX6jg8EYTRip1B/pAnx+SNL/m4QmCv70jlcSNyes6D+gS1729a755mF3A2aFswlNj0OnLGcserRmgnBlgg2/Mzmq9L3vfIzTaCsgw1CIsdPOoaGxiyWtJXHbRhJ+bFTwh6IKEi/ENFYEEShoc9+khOQHRxui4Td0ITay/MyAlroHQT71Ol3l0vKQnLMRUN5PjvaCiETxeCMnMZ+XjWpUhT8TuZjXpyMj2RIDoLtuZ4mZNb44zr3K/54mQIp3QYUOs4d79SxBsNtE0VLL7CkbJdgNDiUOUC4E0DZEo8gXI8ZcZBVCq4B245azAiT+KBxhzpzHLJp6VlCs4h/E2FJeKqeACQmMDd+vKMWkrM3Qdoy5h7yOcsIZ6oQg4LT8RY+zogdAwaB/5C1tC3h4pCRsOq8TM8+DsiZBH9+GzGOtyhMZsFw7ltGv/jkW7W3CmzUp/PF8VFkQNuihNOpTrTGXaytfiNQHOIQ8huH9/99dD8N9g9tVgtm+XQj8MbiQpHkH6GT5OoPZUJZ1mVmG7fSIEPqQTIvnoz1BZz9rQa4="
    distributions: sdist bdist_wheel
    on:
      tags: true
