language: python
python:
- 3.6

install:
- pip install pipenv
- pipenv install --dev

script:
- pipenv run lint

deploy:
  provider: pypi
  user: max-wittig
  password:
    secure: dFfBZYdQ6zkNX1+h4MEAoQCXspF6NG6k+9sW1iK6xbaVSBc+4OQ9OBO8z66B3z0kdgOk9o7/7GNs3h2GYC9exxQ6xJOSh0ITlqXeFVCF+PPdtZyKHChdcitA1K//zfwUNatVzdZFMEkQQD6NlMmdcOXeCRK+ie8xV6OOfvw7z4iKrAUAEaFoey1zZlefG9a71cJHmz7NlR0G/N8ytQZM7kceFB+cGPO/v+ub0w0jNzYpYtCh9IwAeOc6T6cs2W5kdypd/aJIwvLgbITjIHSPvXq7iw1g5FCMoOmcImw9ctdSKhzKDTaDl1TmqTWl0LqUNvMre+narTi6Bn4ydHW2JXIZtoMjxq44iP7XQMQ/85iYVHYcJDP+IULX/sYgmPmt+TbV5VNFKPGr4lNGu+nrTUpVIHj12/r4OESU3mXkXJlnk/2qt73LY/YBHXoDmgW0a/aTqkqBudBPrmOCFqgWSIaeWW7O67i238zyRglPRNpgfOuOkndASQxhI1zUq4fy77t59uHHyxTE5EaNU0rQdL7Q7eMo9fSDJBdOhLtY492cDWbia8NEf3J8F3y2WJF2ipSUP55MFlevIggJL0acRce0hPyMtbCuGEZQG6Ke+uB4s785ZNI1k2VKD69/l/E16qof/k6GhXL+XiA8tlZIjgB1h0/sXF/Ay2N6B1lE0+8=
  on:
    tags: true
